//
//  OSLogHandler.swift
//  PyanLogger
//
//  Created by Perceval Archimbaud on 01/03/2026.
//

#if canImport(os)

import Foundation
import os

/// A `LogHandler` that routes swift-log messages to Apple's unified logging system (`os.Logger`).
///
/// Each `OSLogHandler` maps its subsystem to the `label` and its category to
/// ``LogHandlerWithCategory/category``. Log levels are translated to the
/// corresponding `os.Logger` methods (e.g. `.warning` maps to `osLogger.warning`).
///
/// Log output is by default formatted as:
/// ```
/// [LEVEL][Source] Message
/// > key = value | key = value
/// ```
///
/// The metadata layout can be customized by passing a ``MetadataStyle`` at
/// initialization. The default style is ``MetadataStyle/oneLine``.
///
/// Metadata from the handler, its provider, and per-message metadata are merged
/// and flattened before being appended.
public struct OSLogHandler: LogHandlerWithCategory {
	private let label: String
	private var osLogger: os.Logger

	public var category: String {
		didSet { osLogger = os.Logger(subsystem: label, category: category) }
	}
	private let metadataStyle: MetadataFormatter.MetadataStyle

	public var logLevel: Logging.Logger.Level = .info
	public var metadata: Logging.Logger.Metadata = [:]
	public var metadataProvider: Logging.Logger.MetadataProvider?

	/// Creates a handler that logs to the unified logging system.
	///
	/// - Parameters:
	///   - label: The subsystem identifier (typically a reverse-DNS string).
	///   - category: The initial logging category.
	///   - metadataStyle: The style used to format metadata in the log output.
	///   - metadataProvider: An optional provider for dynamic metadata.
	public init(
		label: String,
		category: String,
		metadataStyle: MetadataFormatter.MetadataStyle = .oneLine,
		metadataProvider: Logging.Logger.MetadataProvider? = nil
	) {
		self.label = label
		self.category = category
		self.metadataStyle = metadataStyle
		self.osLogger = os.Logger(subsystem: label, category: category)
		self.metadataProvider = metadataProvider
	}

	public func log(
		level: Logging.Logger.Level,
		message: Logging.Logger.Message,
		metadata: Logging.Logger.Metadata?,
		source: String,
		file: String,
		function: String,
		line: UInt
	) {
		let message = formatMessage(
			level: level,
			message: message,
			metadata: metadata,
			source: source,
			file: file,
			function: function,
			line: line
		)

		// Let os.Logger to the mapping for us, since methods for all levels are available
		switch level {
		case .trace: osLogger.trace("\(message, privacy: .public)")
		case .debug: osLogger.debug("\(message, privacy: .public)")
		case .info: osLogger.info("\(message, privacy: .public)")
		case .notice: osLogger.notice("\(message, privacy: .public)")
		case .warning: osLogger.warning("\(message, privacy: .public)")
		case .error: osLogger.error("\(message, privacy: .public)")
		case .critical: osLogger.critical("\(message, privacy: .public)")
		}
	}

	public subscript(metadataKey key: String) -> Logging.Logger.Metadata.Value? {
		get {
			return self.metadata[key]
		}
		set {
			self.metadata[key] = newValue
		}
	}
}

extension OSLogHandler {
	func formatMessage(
		level: Logging.Logger.Level,
		message: Logging.Logger.Message,
		metadata: Logging.Logger.Metadata?,
		source: String,
		file: String,
		function: String,
		line: UInt
	) -> String {
		// Merge handler metadata with message metadata
		let combinedMetadata = Self.prepareMetadata(
			base: self.metadata,
			provider: metadataProvider,
			explicit: metadata
		)

		// Other relevant info are generated by OSLog directly:
		// timestamp, bundle, library (that's matching source)

		// Header
		let sourcePrefix = source != Self.currentModule(fileID: (file)) ? "[\(source)]" : ""
		let header = "[\(level.rawValue.uppercased())]\(sourcePrefix)"

		// Metadata

		let formatter = MetadataFormatter(style: metadataStyle)
		let metadataString = formatter.string(for: combinedMetadata ?? [:])
		let metadataSuffix = metadataString != nil ? "\n\(metadataString!)" : ""

		return "\(header) \(message)\(metadataSuffix)"
	}

	static func prepareMetadata(
		base: Logging.Logger.Metadata,
		provider: Logging.Logger.MetadataProvider?,
		explicit: Logging.Logger.Metadata?
	) -> Logging.Logger.Metadata? {
		var metadata = base

		let provided = provider?.get() ?? [:]
		let explicited = explicit ?? [:]

		if !provided.isEmpty {
			metadata.merge(provided, uniquingKeysWith: { _, provided in provided })
		}

		if !explicited.isEmpty {
			metadata.merge(explicited, uniquingKeysWith: { _, explicited in explicited })
		}

		return metadata
	}
}

extension OSLogHandler {
	static func currentModule(fileID: String = #fileID) -> String {
		let utf8All = fileID.utf8
		if let slashIndex = utf8All.firstIndex(of: UInt8(ascii: "/")) {
			return String(fileID[..<slashIndex])
		} else {
			return "n/a"
		}
	}
}

#endif
